### ISSUE TITLE
All Statistics dissapeared

### ISSUE THREAD

**Issue by jjiglesiasg** [hotosm/osm-analytics#103]
Hi, all Statatistics for my country=Bolivia dissapeared and seems not to have any data since 2004, for any of the features.

Please advise, first was the data frozzen to April 3,2020; now there is no data at all

BsRgds JJ

**Comment by jjiglesiasg** [comment]
Any update? Now the data dissapeared for all countries, and no statistics are shown, I guess data is still from April 3 2020.

It will be updated sometime in the future or the project will be discontinued?

**Comment by tyrasd** [comment]
sorry, there were some issues caused by the switch to a new data provider (see https://github.com/hotosm/osm-analytics-cruncher/issues/20). it should now work again as expected.
