### ISSUE TITLE
Data shows to be almost one month old

### ISSUE THREAD

**Issue by jjiglesiasg** [hotosm/osm-analytics#115]
All reports seems to be almost one month old data

**Comment by jjiglesiasg** [comment]
Now hit the two (2) months old data

**Comment by jjiglesiasg** [comment]
However the screen said that the data is 2 days old, the numbers depicted for all elements are the same than 75 days ago. So where come from this August 29 data upadate if all the values are out-of-date?

**Comment by tyrasd** [comment]
sorry, there were some technical issues in the updating process, which have been fixed by now: Everything should be updated regularly again.
