### ISSUE TITLE
DATA HAS TOO MUCH TIME OUT OF DATE- 3 MONTHS and NO ACTION FROM @HOTOSM (2023-09-06)

### ISSUE THREAD

**Issue by jjiglesiasg** [hotosm/osm-analytics#138]
2023-08-14: The counter indicate more than 2 months with out-of-date Data

**Comment by jjiglesiasg** [comment]
2023-09-06: 3 MONTHS and the DATA REMAINS OUT OF DATE 

@HOTOSM ANY ACTION? or will remain in that way forever?

**Comment by jjiglesiasg** [comment]
2023-09-27: More than 3 MONTHS the the DATA REMAINS OUT OF DATE....

**Comment by jjiglesiasg** [comment]
2023-10-23 the webpage shows data updated 25 days ago. However all statuses shows that the data for statistics has not been updated since 20 June-2023.

The app is useless in this way

**Comment by tyrasd** [comment]
Hi @jjiglesiasg, there was a misconfiguration on the server which caused the latest update time to falsely be "updated" a few weeks ago. The data is indeed still from June 20-ish, which is now again displayed correctly on the website. :bow: 

The cause for the missing updates is the upstream data provided as osm-qa-tiles, which did not get any updates after https://github.com/osmlab/osm-qa-tiles/pull/36. I had already reached out privately to @dakotabenjamin about this issue a few weeks back, but did not yet get a reply about what the current status of the osm-qa-tiles is. So I'm bascially about as lost on this as you are, unfortunately.

I'd recommend to open an issue over at the osm-qa-tiles repo: https://github.com/osmlab/osm-qa-tiles/issues
