### ISSUE TITLE
Ecuador search doesn't work

### ISSUE THREAD

**Issue by cgiovando** [hotosm/osm-analytics#25]
Not sure if a problem with nominatim or actual boundary map feature.... Earlier today searching "Ecuador" would find it correctly (as for any other country), but right now it does not work.

**Comment by tyrasd** [comment]
oh, someone accidentally changed Ecuador's boundary relation into a no-u-turn turn restriction. See version 344 here: http://osmlab.github.io/osm-deep-history/#/relation/108089

I've fixed it [now](http://www.openstreetmap.org/changeset/38752175).
