### ISSUE TITLE
Add HOT projects overlay

### ISSUE THREAD

**Issue by cgiovando** [hotosm/osm-analytics#28]
As discussed, there should be an option to show an overlay of all HOT projects. It could be the simplified geometry version to start, then using vector tiles or some sort of heat-map rendering (at low Z levels), should be the actual geometry resolution.

The layer on/off switch could be positioned in the results bar, near the "HOT Projects" text.

**Comment by tyrasd** [comment]
done in 7e977c3a415ce8a0e3677324a0d8bf98df9b8c3a. (simplified geometries for now)

It's enableable via the small context menu of the "HOT projects" in the stats bar (see screenshot). Is it too hidden there?
![selection_015](https://cloud.githubusercontent.com/assets/1927298/14788057/89491920-0b06-11e6-9f52-adbde14553ed.png)

**Comment by cgiovando** [comment]
Thanks @tyrasd - I think that's a great start!

We should really look into what it takes to have more detailed extents though, as some of the smaller shapes become very distorted after simplification. What's the overhead? Is it for display performance or running the intersect functions?

We should also add the TM projects import to the daily cron, so that we have updated extents.

**Comment by tyrasd** [comment]
> What's the overhead?

The issue is mostly the file size of the project geometries (it's around [50MB](https://github.com/pratikyadav/HOT-Task-Map/blob/master/HOT-footprint.geojson) uncompressed GeoJSON). Including individual tasks of each project would blow this up even more.

Having it as a vector tile source would probably solve the issues…

> updated extents

see https://github.com/hotosm/osm-analytics-cruncher/issues/2

**Comment by tyrasd** [comment]
> Having it as a vector tile source would probably solve the issues…

done that.

But I'm noticing that TM's [API](https://github.com/hotosm/osm-tasking-manager2/wiki/API#list-of-projects) apparently doesn't return *archived* projects such as [1838](http://tasks.hotosm.org/project/1838). Let's open a ticket there.
