### ISSUE TITLE
Add "Last Update"

### ISSUE THREAD

**Issue by cgiovando** [hotosm/osm-analytics#29]
Add a note, either in the results tab or directly on the map, which indicates when was the data last updated.

**Comment by tyrasd** [comment]
Now the timestamp of the finished data run is included in the map legend (to get the underlying OSM extract timestamp, one has to subtract another 12-24 hours from that): 
![selection_014](https://cloud.githubusercontent.com/assets/1927298/14784310/46ff4bea-0af5-11e6-9e8e-bf3454de94ea.png)
