### ISSUE TITLE
archived OSM TM jobs don't show up

### ISSUE THREAD

**Issue by mikelmaron** [hotosm/osm-analytics#42]
even after a job is archived on the OSM TM, we want to get stats on it

**Comment by tyrasd** [comment]
yes. this will be fixed automatically with the next update of the TM API: https://github.com/hotosm/osm-tasking-manager2/issues/787. see also https://github.com/hotosm/osm-analytics-cruncher/commit/448d40b8cbaa02f057d61b4eb8d58eaf9925bcc1

**Comment by mikelmaron** [comment]
@tyrasd @pgiraud has this been deployed? would be excellent to see all the sri lanka tasks, for stats

**Comment by tyrasd** [comment]
//cc @ethan-nelson

**Comment by pgiraud** [comment]
@mikelmaron No this hasn't been released nor deployed yet unfortunately.

**Comment by PaulUithol** [comment]
@bgirardot and @smit1678, just ran into this as well.. is this on the agenda for TM3?
