### ISSUE TITLE
OSM Analytics not launching

### ISSUE THREAD

**Issue by mikelmaron** [hotosm/osm-analytics#48]
spinning!
![screen shot 2016-06-07 at 2 35 54 pm](https://cloud.githubusercontent.com/assets/22896/15870125/3430e6d8-2cbd-11e6-97d5-1437c0d49360.png)
 52.207.244.74 is unreachable, at least one problem

@dodobas @tyrasd

**Comment by cgiovando** [comment]
@tyrasd @dodobas - this is probably because of the degrading instance I mentioned in my email from 5/27. Can we get it migrated to a new machine ASAP? Thank you!

We should also have some monitoring system in place and possibly a backup service? I'll submit a separate issue.

**Comment by dodobas** [comment]
Hi,

It's my 'doing' i was creating migration image... so processing is disabled ...

It took 4h to create the image... i'll deploy new instance tomorrow morning UTC and switch frontend to it...

On 7 June 2016 20:43:53 CEST, Cristiano Giovando <notifications@github.com> wrote:
>@tyrasd @dodobas - this is probably because of the degrading instance I
>mentioned in my email from 5/27. Can we get it migrated to a new
>machine ASAP? Thank you!
>
>We should also have some monitoring system in place and possibly a
>backup service? I'll submit a separate issue.
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/hotosm/osm-analytics/issues/48#issuecomment-224375900

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by dodobas** [comment]
hmm, now i see it ... ok, it was not clear on the cell phone ... 

while creating an 'image' the server was restarted... it's possible that some service did not start up... or it changed the IP address... 

I do know that processing is not active, but this seems like the tileserver is not reachable, is this really urgent or it can wait for half a day, as I need to get back to the office and check on my laptop

**Comment by mikelmaron** [comment]
was hoping to share this at a meeting today, but can't...

will it be fully back and up to date tomorrow?

**Comment by dodobas** [comment]
this is the plan:
* create new subdomain: da-tiles.osm-analytics.org
* start new osm-da cruncher (tile server)
* assign elastic IP address for the osm-da tile server
* reconfigure frontend to use the new subdomain (less issues when migrating services)
* shutdown old instance

**Comment by cgiovando** [comment]
Sounds good @dodobas - keep us posted

FYI - I filed #49 and https://github.com/hotosm/osm-analytics-cruncher/issues/7

**Comment by tyrasd** [comment]
Now it works again. :relieved: @dodobas: can you please also push the updated vector tile source (da-tiles.osm-analytics.org) to the master branch as well?
