### ISSUE TITLE
Error because of OSM region simplification?

### ISSUE THREAD

**Issue by cgiovando** [hotosm/osm-analytics#51]
Searching for San Diego throws the following error:

`bundle.js:46309 error during osm region search: j…s.e…r.TopologyError {name: "TopologyError", message: "found non-noded intersection between LINESTRING ( …15 ) [ (-116.95579819155904, 33.09357074019966) ]"}`

The San Diego city outline is found and created, but it looks like the simplification method creates a topological error with the boundary line self-intersecting:

<img width="512" alt="screen shot 2016-06-17 at 16 35 38" src="https://cloud.githubusercontent.com/assets/10201533/16167428/a51b9d90-34a9-11e6-8e2a-a472d4811cbb.png">

That is most likely created because of the complex city boundary in that area:

<img width="512" alt="screen shot 2016-06-17 at 16 37 48" src="https://cloud.githubusercontent.com/assets/10201533/16167450/e67a61f4-34a9-11e6-9daa-597abd8af134.png">

Maybe it's possible to adjust the amount of simplification factor that OSMA performs when creating these regions to try to avoid these issues, which seem to be quite frequent for cities (e.g. Los Angeles and Santa Barbara have the same problem)?

**Comment by tyrasd** [comment]
this should be fixed with cc6029f906eec3e1353ff42fe395dfc0ec67224e
