### ISSUE TITLE
2012 license change redactions

### ISSUE THREAD

**Issue by AntonKhorev** [hotosm/osm-analytics#57]
Consider adding a warning that data before 2013 may be affected by [license change redactions](https://blog.openstreetmap.org/2012/07/26/automated-redactions-complete/). Some features that were mapped back then are not displayed. For example, this includes roughly all of the roads in Saint Petersburg.

**Comment by tyrasd** [comment]
Hi, thanks for your comment, and excuse the late reply. You're right, but at the moment the osm-analytics tool only shows the "latest modification" timestamp of objects that are still present in a current osm planet dump, so any data that was deleted (for example in the license change process) is not included at all on the map and the displayed graphs. This is a known [(and documented) limitation](https://github.com/hotosm/osm-analytics#limitations).
