### ISSUE TITLE
km of Roads not working

### ISSUE THREAD

**Issue by cgiovando** [hotosm/osm-analytics#63]
When selecting an area (custom or via search box) the returned number for km of roads is always 0 (zero).

The same problem happens with the comparison (historic) view.

**Comment by tyrasd** [comment]
confirming. although it still works on high zoom levels, e.g. http://osm-analytics.org/#/compare/bbox:8.65254,49.38577,8.73719,49.41154/2008...2009/highways

first guess: might be related to 4bf821330f1369e959ce96575e9562a0c6c00c66

**Comment by mataharimhairi** [comment]
Just stumbled across this issue too when trying to grab road statistics for Indonesia. Buildings are fine but there is no data for KM, Miles or Trips to the Moon! I also noticed that the last data update listed on the page for roads was 3 months ago, while it was only 11 hours for buildings. 

<img width="1034" alt="screen shot 2017-03-31 at 11 10 02" src="https://cloud.githubusercontent.com/assets/8972913/24534879/3e5f863e-1603-11e7-956f-cf2bfc9912b1.png">

<img width="1035" alt="screen shot 2017-03-31 at 11 10 54" src="https://cloud.githubusercontent.com/assets/8972913/24534885/44fa7120-1603-11e7-83b2-9ece084d8029.png">

**Comment by tiagojsag** [comment]
Hi everyone,

In "our" cruncher we had an issue with tiles not being generated on some zoom levels, which I believe is also what's happening here. We believe the following commit fixes it:

https://github.com/GFDRR/osm-analytics-cruncher/commit/31a572214a029e7d7f499f8392aa3e96390ba417

(kudos to @rrequero for the fix)

We are already testing it on our clone of the cruncher + API, seems to fix the problem

Thanks

**Comment by cgiovando** [comment]
Thanks, @tiagojsag - can you please send a PR with the fix?

Also, I'm assuming your improved cruncher is in the [staging branch](https://github.com/GFDRR/osm-analytics-cruncher/tree/staging) - can we merge that with master [here](https://github.com/hotosm/osm-analytics-cruncher/tree/master)?
