### ISSUE TITLE
OSMA not loading

### ISSUE THREAD

**Issue by cgiovando** [hotosm/osm-analytics#95]
![Screen Shot 2019-10-10 at 10 42 34](https://user-images.githubusercontent.com/10201533/66553112-d0851280-eb4a-11e9-8afa-76d02e565be6.jpg)

**Comment by ramyaragupathy** [comment]
This is because of TM service outage @cgiovando - @eternaltyro is investigating on the issue

**Comment by cgiovando** [comment]
Thanks @ramyaragupathy - wondering if there may be also another issue, as I think the map should load even if TM projects are not available? What do you think @tyrasd ?

**Comment by cgiovando** [comment]
Closing for now, as it seems it was related to the TM outage, but we should still look into how we can make it work even if TM becomes unavailable.
