### ISSUE TITLE
Add Place= as one of the main metrics tool

### ISSUE THREAD

**Issue by jjiglesiasg** [hotosm/osm-analytics#97]
As Roads, Buildings, Rivers; Place tag should be a Very good Metric to know.

Thanks

**Comment by cgiovando** [comment]
Hi @jjiglesiasg - can you please send a PR against this configuration file with the proposed addition? https://github.com/hotosm/osm-analytics-config/blob/master/analytics.json

I believe the OSMA Cruncher reads that files directly and new layers would be added automatically to the website. Maybe the only place where new data would not be available, is the `Comparison View` tool - correct @tyrasd ?

**Comment by tyrasd** [comment]
@cgiovando you are right, the config file is fetched automatically, and with the next data update any new layers are on the map. Only the historic data for the "compare time periods" feature would not be available without manual intervention.

**Comment by jjiglesiasg** [comment]
I am Not reallu sure of how to place a Pull Request, but could be very nice if Tag:place could be added to the main metrics, like highways, buildings, amenities and hospitals

Thanks if you can help about

> Hi @jjiglesiasg - can you please send a PR against this configuration file with the proposed addition? https://github.com/hotosm/osm-analytics-config/blob/master/analytics.json
> 
> I believe the OSMA Cruncher reads that files directly and new layers would be added automatically to the website. Maybe the only place where new data would not be available, is the `Comparison View` tool - correct @tyrasd ?

**Comment by cgiovando** [comment]
Hi @jjiglesiasg - I added places in this PR https://github.com/hotosm/osm-analytics-config/pull/2

@tyrasd please merge if it looks OK :)

**Comment by jjiglesiasg** [comment]
Thanks and Best Regards

**Comment by tyrasd** [comment]
It is merged now and should appear with the next data update in about 1 1/2 day.

**Comment by tyrasd** [comment]
in the meantime the new _places_ layer is online (after a small scaling adjustment in https://github.com/hotosm/osm-analytics-config/commit/53bb76285136aa43de98d91c7a08308b33357734 and https://github.com/hotosm/osm-analytics-config/commit/7609ed8dc72dbf5371940b91cd7a8f2d0d500966 to make the heatmap look a bit better).
