### ISSUE TITLE
App not loading, needs new TM API endpoint

### ISSUE THREAD

**Issue by cgiovando** [hotosm/osm-analytics#99]
With the new TM4 :heart_eyes:, it looks like the API endpoint might have changed.

![Screen Shot 2020-05-06 at 18 17 25](https://user-images.githubusercontent.com/10201533/81202551-11e97d80-8fc7-11ea-8b1e-51500f10096d.jpg)

@dakotabenjamin @xamanu can you please provide the updated endpoint for `https://tasks.hotosm.org/api/v1/project/search`?

cc @tyrasd

**Comment by willemarcel** [comment]
@cgiovando https://github.com/hotosm/osm-analytics/pull/100
